# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x04\x41uth\"1\n\x0b\x41uthRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"/\n\x0c\x41uthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"!\n\x12JWTValidateRequest\x12\x0b\n\x03jwt\x18\x01 \x01(\t\"$\n\x13JWTValidateResponse\x12\r\n\x05valid\x18\x01 \x01(\x08\"(\n\x15JWTInvalidateResponse\x12\x0f\n\x07\x64\x65leted\x18\x01 \x01(\x08\x32\xd1\x01\n\x0c\x41uthenticate\x12\x37\n\x0c\x61uthenticate\x12\x11.Auth.AuthRequest\x1a\x12.Auth.AuthResponse\"\x00\x12\x41\n\x08validate\x12\x18.Auth.JWTValidateRequest\x1a\x19.Auth.JWTValidateResponse\"\x00\x12\x45\n\ninvalidate\x12\x18.Auth.JWTValidateRequest\x1a\x1b.Auth.JWTInvalidateResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUTHREQUEST']._serialized_start=20
  _globals['_AUTHREQUEST']._serialized_end=69
  _globals['_AUTHRESPONSE']._serialized_start=71
  _globals['_AUTHRESPONSE']._serialized_end=118
  _globals['_JWTVALIDATEREQUEST']._serialized_start=120
  _globals['_JWTVALIDATEREQUEST']._serialized_end=153
  _globals['_JWTVALIDATERESPONSE']._serialized_start=155
  _globals['_JWTVALIDATERESPONSE']._serialized_end=191
  _globals['_JWTINVALIDATERESPONSE']._serialized_start=193
  _globals['_JWTINVALIDATERESPONSE']._serialized_end=233
  _globals['_AUTHENTICATE']._serialized_start=236
  _globals['_AUTHENTICATE']._serialized_end=445
# @@protoc_insertion_point(module_scope)
